### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by kholthaus** [d21spike/plugin.video.sling#43]
As of 3/14/22, I received an error when trying to play Sling content (Kodi Leia, RPi 4). The error message in the log:
`
2022-03-16 06:02:01.310 T:1622995840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sling/default.py", line 26, in <module>
                                                if __name__ == '__main__': sling.Sling(sys.argv).run()
                                              File "/storage/.kodi/addons/plugin.video.sling/resources/lib/sling.py", line 77, in run
                                                if self.mode == "play": self.play()
                                              File "/storage/.kodi/addons/plugin.video.sling/resources/lib/sling.py", line 243, in play
                                                if not is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 72, in http_get
                                                log(0, 'Response: {response}', response=content)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py", line 305, in log
                                                message = Formatter().vformat(message, (), SafeDict(**kwargs))
                                              File "/usr/lib/python2.7/string.py", line 563, in vformat
                                              File "/usr/lib/python2.7/string.py", line 598, in _vformat
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            -->End of Python script error report<--
`

It appears that changing line 73 in `/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py` to read
`
return content.decode('UTF-8')
`
fixes the problem.

However, I'm neither a Python programmer, nor do I have any experience with programming this or any other Kodi plugin - so somebody should probably verify whether this is truly an issue, and whether changing that return line is truly the fix.

**Comment by d21spike** [comment]
@kholthaus sorry for the late response. I just tried Kodi 18.4 without issue. Are you still having problems?

**Comment by kholthaus** [comment]
@d21spike I've been running with the change I mentioned in my post since March, and everything is running fine. It's LibreElec 9.2.8 (which is Kodi 18.9) on a Raspberry Pi 4.
I can't quite recall if I had 18.9 in March, but I don't think I've done any updates since then (as LibreElec 10/Kodi 19 doesn't seem to be quite ready 'across the board' yet). So, chances are this error report was based on those versions.
