### ISSUE TITLE
Sling has moved to support multi profiles.  Won't log in anymore

### ISSUE THREAD

**Issue by smallmountains** [d21spike/plugin.video.sling#56]
Getting a Sling error relating to username and password.
Log into Sling.com, asks for user to select the profile to use before getting to the guide.
Sling addon no longer works at all.

**Comment by ParetoOptimalDev** [comment]
I also can't login, not sure if same cause.

Here is my error:

```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
		 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
		Error Type: <class 'requests.exceptions.JSONDecodeError'>
		Error Contents: Expecting value: line 1 column 1 (char 0)
		Traceback (most recent call last):
		  File "/nix/store/h499hd9y26ba024xffv192rsrp8fabxs-kodi-20.2-env/share/kodi/addons/script.module.requests/lib/requests/models.py", line 971, in json
		    return complexjson.loads(self.text, **kwargs)
			   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
		  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/json/__init__.py", line 346, in loads
		    return _default_decoder.decode(s)
			   ^^^^^^^^^^^^^^^^^^^^^^^^^^
		  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/json/decoder.py", line 337, in decode
		    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
			       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
		  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/json/decoder.py", line 355, in raw_decode
		    raise JSONDecodeError("Expecting value", s, err.value) from None
		json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

		During handling of the above exception, another exception occurred:

		Traceback (most recent call last):
		  File "/nix/store/h499hd9y26ba024xffv192rsrp8fabxs-kodi-20.2-env/share/kodi/addons/plugin.video.sling/default.py", line 26, in <module>
		    if __name__ == '__main__': sling.Sling(sys.argv).run()
					       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
		  File "/nix/store/h499hd9y26ba024xffv192rsrp8fabxs-kodi-20.2-env/share/kodi/addons/plugin.video.sling/resources/lib/sling.py", line 63, in run
		    loggedIn, message = self.auth.logIn(self.endPoints, USER_EMAIL, USER_PASSWORD)
					^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
		  File "/nix/store/h499hd9y26ba024xffv192rsrp8fabxs-kodi-20.2-env/share/kodi/addons/plugin.video.sling/resources/lib/classes/auth.py", line 258, in logIn
		    gotOTK, message = self.getOTK(endPoints)
				      ^^^^^^^^^^^^^^^^^^^^^^
		  File "/nix/store/h499hd9y26ba024xffv192rsrp8fabxs-kodi-20.2-env/share/kodi/addons/plugin.video.sling/resources/lib/classes/auth.py", line 196, in getOTK
		    response_json = response.json()
				    ^^^^^^^^^^^^^^^
		  File "/nix/store/h499hd9y26ba024xffv192rsrp8fabxs-kodi-20.2-env/share/kodi/addons/script.module.requests/lib/requests/models.py", line 975, in json
		    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
		requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
		-->End of Python script error report<--
```

**Comment by ParetoOptimalDev** [comment]
Actually I applied this patch:

```diff
diff --git a/resources/lib/classes/auth.py b/resources/lib/classes/auth.py
index 129b184..24950f4 100644
--- a/resources/lib/classes/auth.py
+++ b/resources/lib/classes/auth.py
@@ -244,6 +244,10 @@ class Auth(object):
         }
         auth = OAuth1(self.OCK, self.OCS)
         response = requests.post('%s/user/lookup' % endPoints['extauth_url'], headers=HEADERS, data=json.dumps(payload), auth=auth, verify=VERIFY)
+        with open("/tmp/error_response_kodi_plugin.video.sling", 'wb') as fd:
+            for chunk in response.iter_content(chunk_size=128):
+                fd.write(chunk)
         response_json = response.json()
         
         if response.status_code == 200:
```

And I see it succeeds.... interesting... wonder what's wrong with the json.

**Comment by ParetoOptimalDev** [comment]
Oh nevermind, the problem is in getOtk:

```python
    def getOTK(self, endPoints):
        log('auth::getOTK()')
        self.deviceID()
        self.getAccess()

        # Validate account
        payload = "email=%s&password=%s&device_guid=%s" % (requests.utils.quote(
            USER_EMAIL), requests.utils.quote(USER_PASSWORD), requests.utils.quote(DEVICE_ID))
        account_headers = HEADERS
        account_headers['Content-Type'] = 'application/x-www-form-urlencoded'
        auth = OAuth1(self.OCK, self.OCS)
        response = requests.put('%s/v3/xauth/access_token.json' %
                                endPoints['ums_url'], headers=account_headers, data=payload, auth=auth, verify=VERIFY)
        with open("/tmp/otk_error_response_kodi_plugin.video.sling_headers", 'w') as fd:
            json.dump(dict(response.headers), fd)
        with open("/tmp/otk_error_response_kodi_plugin.video.sling", 'wb') as fd:
            for chunk in response.iter_content(chunk_size=128):
                fd.write(chunk)
        response_json = response.json()
```

gives:

```
$ cat /tmp/otk_error_response_kodi_plugin.video.sling
<html><head><title>Error Page</title></head>
<body>The requested URL was rejected. Please consult with your administrator.<br/><br/>
Your support ID is bffef10f-f36f-4a84-9f75-79cdd77721a0<h2>Error 403 - Forbidden</h2>F5 site: redacted<br/><br/><a href='javascript:history.back();'>[Go Back]</a></body></html>
```

**Comment by ParetoOptimalDev** [comment]
If it helps logging in manually I don't see "v3/xauth/access_token.json", but I do see a url that seems to have the same request headers:

https://ums.p.sling.com/v5/users/access_from_jwt

**Comment by eracknaphobia** [comment]
I believe if you make the changes below it should work. Please test and let me know.

ORG
```python
account_headers = HEADERS
account_headers['Content-Type'] = 'application/x-www-form-urlencoded'
auth = OAuth1(self.OCK, self.OCS)
```

NEW
```python
account_headers = HEADERS
account_headers['Content-Type'] = 'application/x-www-form-urlencoded; charset=UTF-8'        
account_headers['User-Agent'] = ANDROID_USER_AGENT
auth = OAuth1(self.OCK, self.OCS)
```

**Comment by smallmountains** [comment]
What file is this to be applied to?

**Comment by eracknaphobia** [comment]
In the auth.py file

https://github.com/d21spike/plugin.video.sling/blob/4d05593870ad003e05fa62fc36749711e3dc71a0/resources/lib/classes/auth.py#L191

**Comment by smallmountains** [comment]
My file already has those changes.

**Comment by eracknaphobia** [comment]
It shouldn't it's not in the repo...

The content-type is updated but I think more importantly the user-agent needs set to fix the failed login

**Comment by smallmountains** [comment]
Yep, that would be weird...but true.

**Comment by eracknaphobia** [comment]
I created a release with the changes if you care to try that instead.
https://github.com/eracknaphobia/plugin.video.sling/releases/tag/v2024.01.05

**Comment by smallmountains** [comment]
Ok, so I just started over. Wiped all the EPG, Channels, basically all the
databases under PVR/LiveTV, wiped the sling database, reinstalled the
SlingTV addon and put in my login info.  Fine, I don't get the error
message when I launch the addon like I did before but there's virtually no
content under any menu items.
Under Channels I get no content, under My Favorites I get an error message,
under My TV I get another menu(I'll come back to this one), under On Demand
I get no content, under On Now, I get no content, under Shows, I get the
sub menu (0-9, A-G...etc no content under any of those).  Under My TV
submenus, I get content under Continue Watching, and Favorites but under
Hit Movies I get only 11 items listed, under My Channels I get a list of
channels I have in my fav list, under New Tonight I get an error message
after along search, under Order to Watch, I get content (list of about 20
items or so), under Popular shows I get an error message, under Recommended
I get an error message, under Summer Sports I get an error message.

But I don't use the addon this way.  I almost exclusively rely on the EPG.
I enable the slinger service and Enable epg to IPTV.  I can kick off the
Update Channels function from the addon and it shows it's downloading
channel info, takes about 15 minutes or so. After that I can kick off the
Update Guide function, and it shows it's downloading guide info etc, that
takes a while but when finished no guide data is added to the EPG.

It's a mess man.
